package:
  name: "phibers"
  version: "0.1"

source:
  path: /home/andy/projects/phibers

build:
  noarch: generic
  number: 0

requirements:
  run:
    - python >=3.6
    - prokka >=1.14
    - blast
    - scikit-learn =0.18.0
    - scipy <0.19
    - pandas

test:
  commands:
    - phibers

about:
  summary: Prediction of tail fiber proteins

