package:
  name: "phibers"
  version: "0.1"

source:
  path: /home/andy/projects/phibers

build:
  noarch: generic
  number: 0

requirements:
  run:
    - biopython
    - python=3.6
    - pandas
    - scikit-learn=0.23.2

test:
  commands:
    - phibers -h

about:
  summary: Prediction of tail fiber proteins

